package got.common.entity;

import got.common.entity.animal.GOTEntityBear;
import got.common.entity.animal.GOTEntityBearRug;
import got.common.entity.animal.GOTEntityBird;
import got.common.entity.animal.GOTEntityBison;
import got.common.entity.animal.GOTEntityBlizzard;
import got.common.entity.animal.GOTEntityBoar;
import got.common.entity.animal.GOTEntityButterfly;
import got.common.entity.animal.GOTEntityCamel;
import got.common.entity.animal.GOTEntityCrocodile;
import got.common.entity.animal.GOTEntityDeer;
import got.common.entity.animal.GOTEntityDesertScorpion;
import got.common.entity.animal.GOTEntityDikDik;
import got.common.entity.animal.GOTEntityDirewolf;
import got.common.entity.animal.GOTEntityElephant;
import got.common.entity.animal.GOTEntityFish;
import got.common.entity.animal.GOTEntityFlamingo;
import got.common.entity.animal.GOTEntityGemsbok;
import got.common.entity.animal.GOTEntityGiraffe;
import got.common.entity.animal.GOTEntityGiraffeRug;
import got.common.entity.animal.GOTEntityGorcrow;
import got.common.entity.animal.GOTEntityHorse;
import got.common.entity.animal.GOTEntityJungleScorpion;
import got.common.entity.animal.GOTEntityLion;
import got.common.entity.animal.GOTEntityLionRug;
import got.common.entity.animal.GOTEntityLioness;
import got.common.entity.animal.GOTEntityMammoth;
import got.common.entity.animal.GOTEntityManticore;
import got.common.entity.animal.GOTEntityMidges;
import got.common.entity.animal.GOTEntityRabbit;
import got.common.entity.animal.GOTEntityRedScorpion;
import got.common.entity.animal.GOTEntityRhino;
import got.common.entity.animal.GOTEntitySeagull;
import got.common.entity.animal.GOTEntityShadowcat;
import got.common.entity.animal.GOTEntitySnowBear;
import got.common.entity.animal.GOTEntitySwan;
import got.common.entity.animal.GOTEntityTermite;
import got.common.entity.animal.GOTEntityUlthosSpider;
import got.common.entity.animal.GOTEntityWalrus;
import got.common.entity.animal.GOTEntityWhiteBison;
import got.common.entity.animal.GOTEntityWhiteOryx;
import got.common.entity.animal.GOTEntityWoolyRhino;
import got.common.entity.animal.GOTEntityWyvern;
import got.common.entity.animal.GOTEntityZebra;
import got.common.entity.dragon.GOTEntityDragon;
import got.common.entity.essos.GOTEntityEssosBandit;
import got.common.entity.essos.GOTEntityEssosScrapTrader;
import got.common.entity.essos.GOTEntityEssosThief;
import got.common.entity.essos.GOTEntityRedPriest;
import got.common.entity.essos.GOTEntityShryke;
import got.common.entity.essos.GOTEntityStoneMan;
import got.common.entity.essos.gold.GOTEntityGoldenBannerBearer;
import got.common.entity.essos.gold.GOTEntityGoldenCaptain;
import got.common.entity.essos.gold.GOTEntityGoldenSpearman;
import got.common.entity.essos.gold.GOTEntityGoldenWarrior;
import got.common.entity.essos.mossovy.GOTEntityMarshWraith;
import got.common.entity.other.*;
import got.common.entity.other.GOTEntitySpear.GOTEntityThiefKnife;
import got.common.entity.potion.GOTEntityCustomPotion;
import got.common.entity.potion.GOTEntityLingeringBombEffect;
import got.common.entity.potion.GOTEntityLingeringEffect;
import got.common.entity.potion.GOTEntityLingeringPotion;
import got.common.entity.potion.GOTEntitySmoke;
import got.common.entity.potion.GOTEntitySmokeEffect;
import got.common.entity.potion.GOTEntityToxinBomb;
import got.common.entity.westeros.GOTEntityMaester;
import got.common.entity.westeros.GOTEntityMercenary;
import got.common.entity.westeros.GOTEntitySepton;
import got.common.entity.westeros.GOTEntityWesterosBandit;
import got.common.entity.westeros.GOTEntityWesterosScrapTrader;
import got.common.entity.westeros.GOTEntityWesterosThief;
import got.common.entity.westeros.arryn.GOTEntityArrynBaker;
import got.common.entity.westeros.arryn.GOTEntityArrynBannerBearer;
import got.common.entity.westeros.arryn.GOTEntityArrynBartender;
import got.common.entity.westeros.arryn.GOTEntityArrynBlacksmith;
import got.common.entity.westeros.arryn.GOTEntityArrynBrewer;
import got.common.entity.westeros.arryn.GOTEntityArrynButcher;
import got.common.entity.westeros.arryn.GOTEntityArrynCaptain;
import got.common.entity.westeros.arryn.GOTEntityArrynFarmer;
import got.common.entity.westeros.arryn.GOTEntityArrynFarmhand;
import got.common.entity.westeros.arryn.GOTEntityArrynFishmonger;
import got.common.entity.westeros.arryn.GOTEntityArrynFlorist;
import got.common.entity.westeros.arryn.GOTEntityArrynGoldsmith;
import got.common.entity.westeros.arryn.GOTEntityArrynGuard;
import got.common.entity.westeros.arryn.GOTEntityArrynLevyman;
import got.common.entity.westeros.arryn.GOTEntityArrynLevymanArcher;
import got.common.entity.westeros.arryn.GOTEntityArrynLumberman;
import got.common.entity.westeros.arryn.GOTEntityArrynMan;
import got.common.entity.westeros.arryn.GOTEntityArrynMason;
import got.common.entity.westeros.arryn.GOTEntityArrynMiner;
import got.common.entity.westeros.arryn.GOTEntityArrynSoldier;
import got.common.entity.westeros.arryn.GOTEntityArrynSoldierArcher;
import got.common.entity.westeros.crownlands.GOTEntityCrownlandsAlchemist;
import got.common.entity.westeros.crownlands.GOTEntityCrownlandsBaker;
import got.common.entity.westeros.crownlands.GOTEntityCrownlandsBannerBearer;
import got.common.entity.westeros.crownlands.GOTEntityCrownlandsBartender;
import got.common.entity.westeros.crownlands.GOTEntityCrownlandsBlacksmith;
import got.common.entity.westeros.crownlands.GOTEntityCrownlandsBrewer;
import got.common.entity.westeros.crownlands.GOTEntityCrownlandsButcher;
import got.common.entity.westeros.crownlands.GOTEntityCrownlandsCaptain;
import got.common.entity.westeros.crownlands.GOTEntityCrownlandsFarmer;
import got.common.entity.westeros.crownlands.GOTEntityCrownlandsFarmhand;
import got.common.entity.westeros.crownlands.GOTEntityCrownlandsFishmonger;
import got.common.entity.westeros.crownlands.GOTEntityCrownlandsFlorist;
import got.common.entity.westeros.crownlands.GOTEntityCrownlandsGoldsmith;
import got.common.entity.westeros.crownlands.GOTEntityCrownlandsGuard;
import got.common.entity.westeros.crownlands.GOTEntityCrownlandsLevyman;
import got.common.entity.westeros.crownlands.GOTEntityCrownlandsLevymanArcher;
import got.common.entity.westeros.crownlands.GOTEntityCrownlandsLumberman;
import got.common.entity.westeros.crownlands.GOTEntityCrownlandsMan;
import got.common.entity.westeros.crownlands.GOTEntityCrownlandsMason;
import got.common.entity.westeros.crownlands.GOTEntityCrownlandsMiner;
import got.common.entity.westeros.crownlands.GOTEntityKingsguard;
import got.common.entity.westeros.dorne.GOTEntityDorneBaker;
import got.common.entity.westeros.dorne.GOTEntityDorneBannerBearer;
import got.common.entity.westeros.dorne.GOTEntityDorneBartender;
import got.common.entity.westeros.dorne.GOTEntityDorneBlacksmith;
import got.common.entity.westeros.dorne.GOTEntityDorneBrewer;
import got.common.entity.westeros.dorne.GOTEntityDorneButcher;
import got.common.entity.westeros.dorne.GOTEntityDorneCaptain;
import got.common.entity.westeros.dorne.GOTEntityDorneFarmer;
import got.common.entity.westeros.dorne.GOTEntityDorneFarmhand;
import got.common.entity.westeros.dorne.GOTEntityDorneFishmonger;
import got.common.entity.westeros.dorne.GOTEntityDorneFlorist;
import got.common.entity.westeros.dorne.GOTEntityDorneGoldsmith;
import got.common.entity.westeros.dorne.GOTEntityDorneLevyman;
import got.common.entity.westeros.dorne.GOTEntityDorneLevymanArcher;
import got.common.entity.westeros.dorne.GOTEntityDorneLumberman;
import got.common.entity.westeros.dorne.GOTEntityDorneMan;
import got.common.entity.westeros.dorne.GOTEntityDorneMason;
import got.common.entity.westeros.dorne.GOTEntityDorneMiner;
import got.common.entity.westeros.dorne.GOTEntityDorneSoldier;
import got.common.entity.westeros.dorne.GOTEntityDorneSoldierArcher;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneBaker;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneBannerBearer;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneBartender;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneBlacksmith;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneBrewer;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneButcher;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneCaptain;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneFarmer;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneFarmhand;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneFishmonger;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneFlorist;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneGoldsmith;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneLevyman;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneLevymanArcher;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneLumberman;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneMan;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneMason;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneMiner;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneSoldier;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneSoldierArcher;
import got.common.entity.westeros.gift.GOTEntityGiftBannerBearer;
import got.common.entity.westeros.gift.GOTEntityGiftBlacksmith;
import got.common.entity.westeros.gift.GOTEntityGiftGuard;
import got.common.entity.westeros.gift.GOTEntityGiftMan;
import got.common.entity.westeros.hillmen.GOTEntityHillman;
import got.common.entity.westeros.hillmen.GOTEntityHillmanArcher;
import got.common.entity.westeros.hillmen.GOTEntityHillmanAxeThrower;
import got.common.entity.westeros.hillmen.GOTEntityHillmanBannerBearer;
import got.common.entity.westeros.hillmen.GOTEntityHillmanBartender;
import got.common.entity.westeros.hillmen.GOTEntityHillmanBerserker;
import got.common.entity.westeros.hillmen.GOTEntityHillmanWarlord;
import got.common.entity.westeros.hillmen.GOTEntityHillmanWarrior;
import got.common.entity.westeros.ice.GOTEntityIceSpider;
import got.common.entity.westeros.ice.GOTEntityWhiteWalker;
import got.common.entity.westeros.ice.GOTEntityWight;
import got.common.entity.westeros.ice.GOTEntityWightGiant;
import got.common.entity.westeros.ironborn.GOTEntityIronbornBaker;
import got.common.entity.westeros.ironborn.GOTEntityIronbornBannerBearer;
import got.common.entity.westeros.ironborn.GOTEntityIronbornBartender;
import got.common.entity.westeros.ironborn.GOTEntityIronbornBlacksmith;
import got.common.entity.westeros.ironborn.GOTEntityIronbornBrewer;
import got.common.entity.westeros.ironborn.GOTEntityIronbornButcher;
import got.common.entity.westeros.ironborn.GOTEntityIronbornCaptain;
import got.common.entity.westeros.ironborn.GOTEntityIronbornFarmer;
import got.common.entity.westeros.ironborn.GOTEntityIronbornFarmhand;
import got.common.entity.westeros.ironborn.GOTEntityIronbornFishmonger;
import got.common.entity.westeros.ironborn.GOTEntityIronbornFlorist;
import got.common.entity.westeros.ironborn.GOTEntityIronbornGoldsmith;
import got.common.entity.westeros.ironborn.GOTEntityIronbornLevyman;
import got.common.entity.westeros.ironborn.GOTEntityIronbornLevymanArcher;
import got.common.entity.westeros.ironborn.GOTEntityIronbornLumberman;
import got.common.entity.westeros.ironborn.GOTEntityIronbornMan;
import got.common.entity.westeros.ironborn.GOTEntityIronbornMason;
import got.common.entity.westeros.ironborn.GOTEntityIronbornMiner;
import got.common.entity.westeros.ironborn.GOTEntityIronbornPriest;
import got.common.entity.westeros.ironborn.GOTEntityIronbornSoldier;
import got.common.entity.westeros.ironborn.GOTEntityIronbornSoldierArcher;
import got.common.entity.westeros.north.GOTEntityNorthBaker;
import got.common.entity.westeros.north.GOTEntityNorthBannerBearer;
import got.common.entity.westeros.north.GOTEntityNorthBartender;
import got.common.entity.westeros.north.GOTEntityNorthBlacksmith;
import got.common.entity.westeros.north.GOTEntityNorthBrewer;
import got.common.entity.westeros.north.GOTEntityNorthButcher;
import got.common.entity.westeros.north.GOTEntityNorthCaptain;
import got.common.entity.westeros.north.GOTEntityNorthFarmer;
import got.common.entity.westeros.north.GOTEntityNorthFarmhand;
import got.common.entity.westeros.north.GOTEntityNorthFishmonger;
import got.common.entity.westeros.north.GOTEntityNorthFlorist;
import got.common.entity.westeros.north.GOTEntityNorthGoldsmith;
import got.common.entity.westeros.north.GOTEntityNorthGuard;
import got.common.entity.westeros.north.GOTEntityNorthLevyman;
import got.common.entity.westeros.north.GOTEntityNorthLevymanArcher;
import got.common.entity.westeros.north.GOTEntityNorthLumberman;
import got.common.entity.westeros.north.GOTEntityNorthMan;
import got.common.entity.westeros.north.GOTEntityNorthMason;
import got.common.entity.westeros.north.GOTEntityNorthMiner;
import got.common.entity.westeros.north.GOTEntityNorthSoldier;
import got.common.entity.westeros.north.GOTEntityNorthSoldierArcher;
import got.common.entity.westeros.north.hillmen.GOTEntityNorthHillman;
import got.common.entity.westeros.north.hillmen.GOTEntityNorthHillmanArcher;
import got.common.entity.westeros.north.hillmen.GOTEntityNorthHillmanAxeThrower;
import got.common.entity.westeros.north.hillmen.GOTEntityNorthHillmanBannerBearer;
import got.common.entity.westeros.north.hillmen.GOTEntityNorthHillmanCannibal;
import got.common.entity.westeros.north.hillmen.GOTEntityNorthHillmanChieftain;
import got.common.entity.westeros.north.hillmen.GOTEntityNorthHillmanMercenary;
import got.common.entity.westeros.north.hillmen.GOTEntityNorthHillmanWarrior;
import got.common.entity.westeros.reach.GOTEntityReachBaker;
import got.common.entity.westeros.reach.GOTEntityReachBannerBearer;
import got.common.entity.westeros.reach.GOTEntityReachBartender;
import got.common.entity.westeros.reach.GOTEntityReachBlacksmith;
import got.common.entity.westeros.reach.GOTEntityReachBrewer;
import got.common.entity.westeros.reach.GOTEntityReachButcher;
import got.common.entity.westeros.reach.GOTEntityReachCaptain;
import got.common.entity.westeros.reach.GOTEntityReachFarmer;
import got.common.entity.westeros.reach.GOTEntityReachFarmhand;
import got.common.entity.westeros.reach.GOTEntityReachFishmonger;
import got.common.entity.westeros.reach.GOTEntityReachFlorist;
import got.common.entity.westeros.reach.GOTEntityReachGoldsmith;
import got.common.entity.westeros.reach.GOTEntityReachGuard;
import got.common.entity.westeros.reach.GOTEntityReachLevyman;
import got.common.entity.westeros.reach.GOTEntityReachLevymanArcher;
import got.common.entity.westeros.reach.GOTEntityReachLumberman;
import got.common.entity.westeros.reach.GOTEntityReachMan;
import got.common.entity.westeros.reach.GOTEntityReachMason;
import got.common.entity.westeros.reach.GOTEntityReachMiner;
import got.common.entity.westeros.reach.GOTEntityReachSoldier;
import got.common.entity.westeros.reach.GOTEntityReachSoldierArcher;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsBaker;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsBannerBearer;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsBartender;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsBlacksmith;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsBrewer;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsButcher;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsCaptain;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsFarmer;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsFarmhand;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsFishmonger;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsFlorist;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsGoldsmith;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsLevyman;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsLevymanArcher;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsLumberman;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsMan;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsMason;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsMiner;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsSoldier;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsSoldierArcher;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsBaker;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsBannerBearer;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsBartender;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsBlacksmith;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsBrewer;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsButcher;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsCaptain;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsFarmer;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsFarmhand;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsFishmonger;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsFlorist;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsGoldsmith;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsLevyman;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsLevymanArcher;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsLumberman;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsMan;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsMason;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsMiner;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsSoldier;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsSoldierArcher;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsBaker;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsBannerBearer;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsBartender;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsBlacksmith;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsBrewer;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsButcher;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsCaptain;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsFarmer;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsFarmhand;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsFishmonger;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsFlorist;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsGoldsmith;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsGuard;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsLevyman;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsLevymanArcher;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsLumberman;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsMan;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsMason;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsMiner;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsSoldier;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsSoldierArcher;
import got.common.entity.westeros.wildling.GOTEntityGiant;
import got.common.entity.westeros.wildling.GOTEntityWildling;
import got.common.entity.westeros.wildling.GOTEntityWildlingArcher;
import got.common.entity.westeros.wildling.GOTEntityWildlingAxeThrower;
import got.common.entity.westeros.wildling.GOTEntityWildlingBannerBearer;
import got.common.entity.westeros.wildling.GOTEntityWildlingChieftain;
import got.common.entity.westeros.wildling.thenn.GOTEntityThenn;
import got.common.entity.westeros.wildling.thenn.GOTEntityThennArcher;
import got.common.entity.westeros.wildling.thenn.GOTEntityThennAxeThrower;
import got.common.entity.westeros.wildling.thenn.GOTEntityThennBannerBearer;
import got.common.entity.westeros.wildling.thenn.GOTEntityThennBerserker;
import got.common.entity.westeros.wildling.thenn.GOTEntityThennBlacksmith;
import got.common.entity.westeros.wildling.thenn.GOTEntityThennMagnar;
import got.common.faction.GOTFaction;

public class GOTEntity {
    public static int id;

    public static void preInit() {
        GOTEntityRegistry.register(GOTEntityBison.class, id++, 7488812);
        GOTEntityRegistry.register(GOTEntityBear.class, id++, 7492416);
        GOTEntityRegistry.register(GOTEntityBird.class, id++, 7451872);
        GOTEntityRegistry.register(GOTEntityButterfly.class, id++, 16119285);
        GOTEntityRegistry.register(GOTEntityCamel.class, id++, 13150061);
        GOTEntityRegistry.register(GOTEntityCrocodile.class, id++, 2896659);
        GOTEntityRegistry.register(GOTEntityDeer.class, id++, 5978669);
        GOTEntityRegistry.register(GOTEntityDesertScorpion.class, id++, 16376764);
        GOTEntityRegistry.register(GOTEntityDikDik.class, id++, 12023867);
        GOTEntityRegistry.register(GOTEntityDirewolf.class, id++, 0x808080);
        GOTEntityRegistry.register(GOTEntityDragon.class, id++, 0x282728);
        GOTEntityRegistry.register(GOTEntityElephant.class, id++, 9605778);
        GOTEntityRegistry.register(GOTEntityFish.class, id++, 7053203);
        GOTEntityRegistry.register(GOTEntityFlamingo.class, id++, 16087966);
        GOTEntityRegistry.register(GOTEntityGemsbok.class, id++, 11759423);
        GOTEntityRegistry.register(GOTEntityGiraffe.class, id++, 13608551);
        GOTEntityRegistry.register(GOTEntityGorcrow.class, id++, 928034);
        GOTEntityRegistry.register(GOTEntityHorse.class, id++, 8601889);
        GOTEntityRegistry.register(GOTEntityJungleScorpion.class, id++, 2630945);
        GOTEntityRegistry.register(GOTEntityWhiteBison.class, id++, 16702665);
        GOTEntityRegistry.register(GOTEntityLion.class, id++, 13345354);
        GOTEntityRegistry.register(GOTEntityLioness.class, id++, 13346908);
        GOTEntityRegistry.register(GOTEntityMammoth.class, id++, 5653040);
        GOTEntityRegistry.register(GOTEntityManticore.class, id++, 0x2B3F19);
        GOTEntityRegistry.register(GOTEntityMidges.class, id++, 5653040);
        GOTEntityRegistry.register(GOTEntityRabbit.class, id++, 9860178);
        GOTEntityRegistry.register(GOTEntityRedScorpion.class, id++, 0x7c0a02);
        GOTEntityRegistry.register(GOTEntityRhino.class, id++, 6118481);
        GOTEntityRegistry.register(GOTEntitySeagull.class, id++, 15920107);
        GOTEntityRegistry.register(GOTEntityShadowcat.class, id++, 0x282728);
        GOTEntityRegistry.register(GOTEntitySnowBear.class, id++, 15594495);
        GOTEntityRegistry.register(GOTEntitySwan.class, id++, 16119285);
        GOTEntityRegistry.register(GOTEntityTermite.class, id++, 0x282728);
        GOTEntityRegistry.register(GOTEntityWalrus.class, id++, 7053203);
        GOTEntityRegistry.register(GOTEntityWhiteOryx.class, id++, 16381146);
        GOTEntityRegistry.register(GOTEntityBoar.class, id++, 6635562);
        GOTEntityRegistry.register(GOTEntityWoolyRhino.class, id++, 5653040);
        GOTEntityRegistry.register(GOTEntityWyvern.class, id++, 2896659);
        GOTEntityRegistry.register(GOTEntityZebra.class, id++, 15000804);
        GOTEntityRegistry.register(GOTEntityShryke.class, id++, 2896659);

        GOTEntityRegistry.register(GOTEntityWesterosBandit.class, id++, 0xBABABA);
        GOTEntityRegistry.register(GOTEntityWesterosThief.class, id++, 0xBABABA);
        GOTEntityRegistry.register(GOTEntityWesterosScrapTrader.class, id++, 0xBABABA);
        GOTEntityRegistry.register(GOTEntityEssosBandit.class, id++, 13345354);
        GOTEntityRegistry.register(GOTEntityEssosThief.class, id++, 13345354);
        GOTEntityRegistry.register(GOTEntityEssosScrapTrader.class, id++, 13345354);

        GOTEntityRegistry.register(GOTEntityProstitute.class, id++, 16087966);
        GOTEntityRegistry.register(GOTEntityMaester.class, id++, 0xffffff);
        GOTEntityRegistry.register(GOTEntitySepton.class, id++, 0xffd700);
        GOTEntityRegistry.register(GOTEntityRedPriest.class, id++, 0x7c0a02);
        GOTEntityRegistry.register(GOTEntityIronbornPriest.class, id++, GOTFaction.IRONBORN);
        GOTEntityRegistry.register(GOTEntityBarrowWight.class, id++, 2896659);
        GOTEntityRegistry.register(GOTEntityMarshWraith.class, id++, 10524036);
        GOTEntityRegistry.register(GOTEntityStoneMan.class, id++, 0xBABABA);
        GOTEntityRegistry.register(GOTEntityMercenary.class, id++, 0xBABABA);

        GOTEntityRegistry.register(GOTEntityWhiteWalker.class, id++, GOTFaction.WHITE_WALKER);
        GOTEntityRegistry.register(GOTEntityWight.class, id++, GOTFaction.WHITE_WALKER);
        GOTEntityRegistry.register(GOTEntityIceSpider.class, id++, GOTFaction.WHITE_WALKER);
        GOTEntityRegistry.register(GOTEntityWightGiant.class, id++, GOTFaction.WHITE_WALKER);

        GOTEntityRegistry.register(GOTEntityWildling.class, id++, GOTFaction.WILDLING);
        GOTEntityRegistry.register(GOTEntityWildlingArcher.class, id++, GOTFaction.WILDLING);
        GOTEntityRegistry.register(GOTEntityWildlingAxeThrower.class, id++, GOTFaction.WILDLING);
        GOTEntityRegistry.register(GOTEntityWildlingBannerBearer.class, id++, GOTFaction.WILDLING);
        GOTEntityRegistry.register(GOTEntityWildlingChieftain.class, id++, GOTFaction.WILDLING);
        GOTEntityRegistry.register(GOTEntityGiant.class, id++, GOTFaction.WILDLING);

        GOTEntityRegistry.register(GOTEntityThenn.class, id++, GOTFaction.WILDLING);
        GOTEntityRegistry.register(GOTEntityThennArcher.class, id++, GOTFaction.WILDLING);
        GOTEntityRegistry.register(GOTEntityThennAxeThrower.class, id++, GOTFaction.WILDLING);
        GOTEntityRegistry.register(GOTEntityThennBannerBearer.class, id++, GOTFaction.WILDLING);
        GOTEntityRegistry.register(GOTEntityThennBerserker.class, id++, GOTFaction.WILDLING);
        GOTEntityRegistry.register(GOTEntityThennMagnar.class, id++, GOTFaction.WILDLING);
        GOTEntityRegistry.register(GOTEntityThennBlacksmith.class, id++, GOTFaction.WILDLING);


        GOTEntityRegistry.register(GOTEntityGiftMan.class, id++, GOTFaction.NIGHT_WATCH);
        GOTEntityRegistry.register(GOTEntityGiftBlacksmith.class, id++, GOTFaction.NIGHT_WATCH);
        GOTEntityRegistry.register(GOTEntityGiftGuard.class, id++, GOTFaction.NIGHT_WATCH);
        GOTEntityRegistry.register(GOTEntityGiftBannerBearer.class, id++, GOTFaction.NIGHT_WATCH);

        GOTEntityRegistry.register(GOTEntityNorthMan.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthLevyman.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthLevymanArcher.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthSoldier.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthSoldierArcher.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthGuard.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthBannerBearer.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthCaptain.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthBlacksmith.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthGoldsmith.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthFarmer.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthFarmhand.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthBartender.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthMiner.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthLumberman.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthMason.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthBrewer.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthFlorist.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthButcher.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthFishmonger.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthBaker.class, id++, GOTFaction.NORTH);

        GOTEntityRegistry.register(GOTEntityNorthHillman.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthHillmanWarrior.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthHillmanCannibal.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthHillmanMercenary.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthHillmanArcher.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthHillmanAxeThrower.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthHillmanBannerBearer.class, id++, GOTFaction.NORTH);
        GOTEntityRegistry.register(GOTEntityNorthHillmanChieftain.class, id++, GOTFaction.NORTH);

        GOTEntityRegistry.register(GOTEntityIronbornMan.class, id++, GOTFaction.IRONBORN);
        GOTEntityRegistry.register(GOTEntityIronbornLevyman.class, id++, GOTFaction.IRONBORN);
        GOTEntityRegistry.register(GOTEntityIronbornLevymanArcher.class, id++, GOTFaction.IRONBORN);
        GOTEntityRegistry.register(GOTEntityIronbornSoldier.class, id++, GOTFaction.IRONBORN);
        GOTEntityRegistry.register(GOTEntityIronbornSoldierArcher.class, id++, GOTFaction.IRONBORN);
        GOTEntityRegistry.register(GOTEntityIronbornBannerBearer.class, id++, GOTFaction.IRONBORN);
        GOTEntityRegistry.register(GOTEntityIronbornCaptain.class, id++, GOTFaction.IRONBORN);
        GOTEntityRegistry.register(GOTEntityIronbornBaker.class, id++, GOTFaction.IRONBORN);
        GOTEntityRegistry.register(GOTEntityIronbornBartender.class, id++, GOTFaction.IRONBORN);
        GOTEntityRegistry.register(GOTEntityIronbornGoldsmith.class, id++, GOTFaction.IRONBORN);
        GOTEntityRegistry.register(GOTEntityIronbornBlacksmith.class, id++, GOTFaction.IRONBORN);
        GOTEntityRegistry.register(GOTEntityIronbornBrewer.class, id++, GOTFaction.IRONBORN);
        GOTEntityRegistry.register(GOTEntityIronbornButcher.class, id++, GOTFaction.IRONBORN);
        GOTEntityRegistry.register(GOTEntityIronbornFarmer.class, id++, GOTFaction.IRONBORN);
        GOTEntityRegistry.register(GOTEntityIronbornFarmhand.class, id++, GOTFaction.IRONBORN);
        GOTEntityRegistry.register(GOTEntityIronbornFishmonger.class, id++, GOTFaction.IRONBORN);
        GOTEntityRegistry.register(GOTEntityIronbornFlorist.class, id++, GOTFaction.IRONBORN);
        GOTEntityRegistry.register(GOTEntityIronbornMiner.class, id++, GOTFaction.IRONBORN);
        GOTEntityRegistry.register(GOTEntityIronbornLumberman.class, id++, GOTFaction.IRONBORN);
        GOTEntityRegistry.register(GOTEntityIronbornMason.class, id++, GOTFaction.IRONBORN);

        GOTEntityRegistry.register(GOTEntityWesterlandsMan.class, id++, GOTFaction.WESTERLANDS);
        GOTEntityRegistry.register(GOTEntityWesterlandsLevyman.class, id++, GOTFaction.WESTERLANDS);
        GOTEntityRegistry.register(GOTEntityWesterlandsLevymanArcher.class, id++, GOTFaction.WESTERLANDS);
        GOTEntityRegistry.register(GOTEntityWesterlandsSoldier.class, id++, GOTFaction.WESTERLANDS);
        GOTEntityRegistry.register(GOTEntityWesterlandsSoldierArcher.class, id++, GOTFaction.WESTERLANDS);
        GOTEntityRegistry.register(GOTEntityWesterlandsGuard.class, id++, GOTFaction.WESTERLANDS);
        GOTEntityRegistry.register(GOTEntityWesterlandsBannerBearer.class, id++, GOTFaction.WESTERLANDS);
        GOTEntityRegistry.register(GOTEntityWesterlandsCaptain.class, id++, GOTFaction.WESTERLANDS);
        GOTEntityRegistry.register(GOTEntityWesterlandsBaker.class, id++, GOTFaction.WESTERLANDS);
        GOTEntityRegistry.register(GOTEntityWesterlandsBartender.class, id++, GOTFaction.WESTERLANDS);
        GOTEntityRegistry.register(GOTEntityWesterlandsBlacksmith.class, id++, GOTFaction.WESTERLANDS);
        GOTEntityRegistry.register(GOTEntityWesterlandsGoldsmith.class, id++, GOTFaction.WESTERLANDS);
        GOTEntityRegistry.register(GOTEntityWesterlandsBrewer.class, id++, GOTFaction.WESTERLANDS);
        GOTEntityRegistry.register(GOTEntityWesterlandsButcher.class, id++, GOTFaction.WESTERLANDS);
        GOTEntityRegistry.register(GOTEntityWesterlandsFarmer.class, id++, GOTFaction.WESTERLANDS);
        GOTEntityRegistry.register(GOTEntityWesterlandsFarmhand.class, id++, GOTFaction.WESTERLANDS);
        GOTEntityRegistry.register(GOTEntityWesterlandsFishmonger.class, id++, GOTFaction.WESTERLANDS);
        GOTEntityRegistry.register(GOTEntityWesterlandsFlorist.class, id++, GOTFaction.WESTERLANDS);
        GOTEntityRegistry.register(GOTEntityWesterlandsMiner.class, id++, GOTFaction.WESTERLANDS);
        GOTEntityRegistry.register(GOTEntityWesterlandsLumberman.class, id++, GOTFaction.WESTERLANDS);
        GOTEntityRegistry.register(GOTEntityWesterlandsMason.class, id++, GOTFaction.WESTERLANDS);

        GOTEntityRegistry.register(GOTEntityRiverlandsMan.class, id++, GOTFaction.RIVERLANDS);
        GOTEntityRegistry.register(GOTEntityRiverlandsLevyman.class, id++, GOTFaction.RIVERLANDS);
        GOTEntityRegistry.register(GOTEntityRiverlandsLevymanArcher.class, id++, GOTFaction.RIVERLANDS);
        GOTEntityRegistry.register(GOTEntityRiverlandsSoldier.class, id++, GOTFaction.RIVERLANDS);
        GOTEntityRegistry.register(GOTEntityRiverlandsSoldierArcher.class, id++, GOTFaction.RIVERLANDS);
        GOTEntityRegistry.register(GOTEntityRiverlandsBannerBearer.class, id++, GOTFaction.RIVERLANDS);
        GOTEntityRegistry.register(GOTEntityRiverlandsCaptain.class, id++, GOTFaction.RIVERLANDS);
        GOTEntityRegistry.register(GOTEntityRiverlandsBaker.class, id++, GOTFaction.RIVERLANDS);
        GOTEntityRegistry.register(GOTEntityRiverlandsBartender.class, id++, GOTFaction.RIVERLANDS);
        GOTEntityRegistry.register(GOTEntityRiverlandsBlacksmith.class, id++, GOTFaction.RIVERLANDS);
        GOTEntityRegistry.register(GOTEntityRiverlandsGoldsmith.class, id++, GOTFaction.RIVERLANDS);
        GOTEntityRegistry.register(GOTEntityRiverlandsBrewer.class, id++, GOTFaction.RIVERLANDS);
        GOTEntityRegistry.register(GOTEntityRiverlandsButcher.class, id++, GOTFaction.RIVERLANDS);
        GOTEntityRegistry.register(GOTEntityRiverlandsFarmer.class, id++, GOTFaction.RIVERLANDS);
        GOTEntityRegistry.register(GOTEntityRiverlandsFarmhand.class, id++, GOTFaction.RIVERLANDS);
        GOTEntityRegistry.register(GOTEntityRiverlandsFishmonger.class, id++, GOTFaction.RIVERLANDS);
        GOTEntityRegistry.register(GOTEntityRiverlandsFlorist.class, id++, GOTFaction.RIVERLANDS);
        GOTEntityRegistry.register(GOTEntityRiverlandsMiner.class, id++, GOTFaction.RIVERLANDS);
        GOTEntityRegistry.register(GOTEntityRiverlandsLumberman.class, id++, GOTFaction.RIVERLANDS);
        GOTEntityRegistry.register(GOTEntityRiverlandsMason.class, id++, GOTFaction.RIVERLANDS);

        GOTEntityRegistry.register(GOTEntityHillman.class, id++, GOTFaction.HILL_TRIBES);
        GOTEntityRegistry.register(GOTEntityHillmanWarrior.class, id++, GOTFaction.HILL_TRIBES);
        GOTEntityRegistry.register(GOTEntityHillmanArcher.class, id++, GOTFaction.HILL_TRIBES);
        GOTEntityRegistry.register(GOTEntityHillmanAxeThrower.class, id++, GOTFaction.HILL_TRIBES);
        GOTEntityRegistry.register(GOTEntityHillmanBerserker.class, id++, GOTFaction.HILL_TRIBES);
        GOTEntityRegistry.register(GOTEntityHillmanBannerBearer.class, id++, GOTFaction.HILL_TRIBES);
        GOTEntityRegistry.register(GOTEntityHillmanWarlord.class, id++, GOTFaction.HILL_TRIBES);
        GOTEntityRegistry.register(GOTEntityHillmanBartender.class, id++, GOTFaction.HILL_TRIBES);

        GOTEntityRegistry.register(GOTEntityArrynMan.class, id++, GOTFaction.ARRYN);
        GOTEntityRegistry.register(GOTEntityArrynLevyman.class, id++, GOTFaction.ARRYN);
        GOTEntityRegistry.register(GOTEntityArrynLevymanArcher.class, id++, GOTFaction.ARRYN);
        GOTEntityRegistry.register(GOTEntityArrynSoldier.class, id++, GOTFaction.ARRYN);
        GOTEntityRegistry.register(GOTEntityArrynSoldierArcher.class, id++, GOTFaction.ARRYN);
        GOTEntityRegistry.register(GOTEntityArrynGuard.class, id++, GOTFaction.ARRYN);
        GOTEntityRegistry.register(GOTEntityArrynBannerBearer.class, id++, GOTFaction.ARRYN);
        GOTEntityRegistry.register(GOTEntityArrynCaptain.class, id++, GOTFaction.ARRYN);
        GOTEntityRegistry.register(GOTEntityArrynBaker.class, id++, GOTFaction.ARRYN);
        GOTEntityRegistry.register(GOTEntityArrynBartender.class, id++, GOTFaction.ARRYN);
        GOTEntityRegistry.register(GOTEntityArrynBlacksmith.class, id++, GOTFaction.ARRYN);
        GOTEntityRegistry.register(GOTEntityArrynGoldsmith.class, id++, GOTFaction.ARRYN);
        GOTEntityRegistry.register(GOTEntityArrynBrewer.class, id++, GOTFaction.ARRYN);
        GOTEntityRegistry.register(GOTEntityArrynButcher.class, id++, GOTFaction.ARRYN);
        GOTEntityRegistry.register(GOTEntityArrynFarmer.class, id++, GOTFaction.ARRYN);
        GOTEntityRegistry.register(GOTEntityArrynFarmhand.class, id++, GOTFaction.ARRYN);
        GOTEntityRegistry.register(GOTEntityArrynFishmonger.class, id++, GOTFaction.ARRYN);
        GOTEntityRegistry.register(GOTEntityArrynFlorist.class, id++, GOTFaction.ARRYN);
        GOTEntityRegistry.register(GOTEntityArrynMiner.class, id++, GOTFaction.ARRYN);
        GOTEntityRegistry.register(GOTEntityArrynLumberman.class, id++, GOTFaction.ARRYN);
        GOTEntityRegistry.register(GOTEntityArrynMason.class, id++, GOTFaction.ARRYN);

        GOTEntityRegistry.register(GOTEntityDragonstoneMan.class, id++, GOTFaction.DRAGONSTONE);
        GOTEntityRegistry.register(GOTEntityDragonstoneLevyman.class, id++, GOTFaction.DRAGONSTONE);
        GOTEntityRegistry.register(GOTEntityDragonstoneLevymanArcher.class, id++, GOTFaction.DRAGONSTONE);
        GOTEntityRegistry.register(GOTEntityDragonstoneSoldier.class, id++, GOTFaction.DRAGONSTONE);
        GOTEntityRegistry.register(GOTEntityDragonstoneSoldierArcher.class, id++, GOTFaction.DRAGONSTONE);
        GOTEntityRegistry.register(GOTEntityDragonstoneBannerBearer.class, id++, GOTFaction.DRAGONSTONE);
        GOTEntityRegistry.register(GOTEntityDragonstoneCaptain.class, id++, GOTFaction.DRAGONSTONE);
        GOTEntityRegistry.register(GOTEntityDragonstoneBaker.class, id++, GOTFaction.DRAGONSTONE);
        GOTEntityRegistry.register(GOTEntityDragonstoneBartender.class, id++, GOTFaction.DRAGONSTONE);
        GOTEntityRegistry.register(GOTEntityDragonstoneBlacksmith.class, id++, GOTFaction.DRAGONSTONE);
        GOTEntityRegistry.register(GOTEntityDragonstoneGoldsmith.class, id++, GOTFaction.DRAGONSTONE);
        GOTEntityRegistry.register(GOTEntityDragonstoneBrewer.class, id++, GOTFaction.DRAGONSTONE);
        GOTEntityRegistry.register(GOTEntityDragonstoneButcher.class, id++, GOTFaction.DRAGONSTONE);
        GOTEntityRegistry.register(GOTEntityDragonstoneFarmer.class, id++, GOTFaction.DRAGONSTONE);
        GOTEntityRegistry.register(GOTEntityDragonstoneFarmhand.class, id++, GOTFaction.DRAGONSTONE);
        GOTEntityRegistry.register(GOTEntityDragonstoneFishmonger.class, id++, GOTFaction.DRAGONSTONE);
        GOTEntityRegistry.register(GOTEntityDragonstoneFlorist.class, id++, GOTFaction.DRAGONSTONE);
        GOTEntityRegistry.register(GOTEntityDragonstoneMiner.class, id++, GOTFaction.DRAGONSTONE);
        GOTEntityRegistry.register(GOTEntityDragonstoneLumberman.class, id++, GOTFaction.DRAGONSTONE);
        GOTEntityRegistry.register(GOTEntityDragonstoneMason.class, id++, GOTFaction.DRAGONSTONE);

        GOTEntityRegistry.register(GOTEntityCrownlandsMan.class, id++, GOTFaction.CROWNLANDS);
        GOTEntityRegistry.register(GOTEntityCrownlandsLevyman.class, id++, GOTFaction.CROWNLANDS);
        GOTEntityRegistry.register(GOTEntityCrownlandsLevymanArcher.class, id++, GOTFaction.CROWNLANDS);
        GOTEntityRegistry.register(GOTEntityCrownlandsGuard.class, id++, GOTFaction.CROWNLANDS);
        GOTEntityRegistry.register(GOTEntityCrownlandsBannerBearer.class, id++, GOTFaction.CROWNLANDS);
        GOTEntityRegistry.register(GOTEntityKingsguard.class, id++, GOTFaction.CROWNLANDS);
        GOTEntityRegistry.register(GOTEntityCrownlandsCaptain.class, id++, GOTFaction.CROWNLANDS);
        GOTEntityRegistry.register(GOTEntityCrownlandsBaker.class, id++, GOTFaction.CROWNLANDS);
        GOTEntityRegistry.register(GOTEntityCrownlandsBartender.class, id++, GOTFaction.CROWNLANDS);
        GOTEntityRegistry.register(GOTEntityCrownlandsBlacksmith.class, id++, GOTFaction.CROWNLANDS);
        GOTEntityRegistry.register(GOTEntityCrownlandsGoldsmith.class, id++, GOTFaction.CROWNLANDS);
        GOTEntityRegistry.register(GOTEntityCrownlandsBrewer.class, id++, GOTFaction.CROWNLANDS);
        GOTEntityRegistry.register(GOTEntityCrownlandsButcher.class, id++, GOTFaction.CROWNLANDS);
        GOTEntityRegistry.register(GOTEntityCrownlandsFarmer.class, id++, GOTFaction.CROWNLANDS);
        GOTEntityRegistry.register(GOTEntityCrownlandsFarmhand.class, id++, GOTFaction.CROWNLANDS);
        GOTEntityRegistry.register(GOTEntityCrownlandsFishmonger.class, id++, GOTFaction.CROWNLANDS);
        GOTEntityRegistry.register(GOTEntityCrownlandsFlorist.class, id++, GOTFaction.CROWNLANDS);
        GOTEntityRegistry.register(GOTEntityCrownlandsMiner.class, id++, GOTFaction.CROWNLANDS);
        GOTEntityRegistry.register(GOTEntityCrownlandsLumberman.class, id++, GOTFaction.CROWNLANDS);
        GOTEntityRegistry.register(GOTEntityCrownlandsMason.class, id++, GOTFaction.CROWNLANDS);
        GOTEntityRegistry.register(GOTEntityCrownlandsAlchemist.class, id++, GOTFaction.CROWNLANDS);

        GOTEntityRegistry.register(GOTEntityStormlandsMan.class, id++, GOTFaction.STORMLANDS);
        GOTEntityRegistry.register(GOTEntityStormlandsLevyman.class, id++, GOTFaction.STORMLANDS);
        GOTEntityRegistry.register(GOTEntityStormlandsLevymanArcher.class, id++, GOTFaction.STORMLANDS);
        GOTEntityRegistry.register(GOTEntityStormlandsSoldier.class, id++, GOTFaction.STORMLANDS);
        GOTEntityRegistry.register(GOTEntityStormlandsSoldierArcher.class, id++, GOTFaction.STORMLANDS);
        GOTEntityRegistry.register(GOTEntityStormlandsBannerBearer.class, id++, GOTFaction.STORMLANDS);
        GOTEntityRegistry.register(GOTEntityStormlandsCaptain.class, id++, GOTFaction.STORMLANDS);
        GOTEntityRegistry.register(GOTEntityStormlandsBaker.class, id++, GOTFaction.STORMLANDS);
        GOTEntityRegistry.register(GOTEntityStormlandsBartender.class, id++, GOTFaction.STORMLANDS);
        GOTEntityRegistry.register(GOTEntityStormlandsBlacksmith.class, id++, GOTFaction.STORMLANDS);
        GOTEntityRegistry.register(GOTEntityStormlandsGoldsmith.class, id++, GOTFaction.STORMLANDS);
        GOTEntityRegistry.register(GOTEntityStormlandsBrewer.class, id++, GOTFaction.STORMLANDS);
        GOTEntityRegistry.register(GOTEntityStormlandsButcher.class, id++, GOTFaction.STORMLANDS);
        GOTEntityRegistry.register(GOTEntityStormlandsFarmer.class, id++, GOTFaction.STORMLANDS);
        GOTEntityRegistry.register(GOTEntityStormlandsFarmhand.class, id++, GOTFaction.STORMLANDS);
        GOTEntityRegistry.register(GOTEntityStormlandsFishmonger.class, id++, GOTFaction.STORMLANDS);
        GOTEntityRegistry.register(GOTEntityStormlandsFlorist.class, id++, GOTFaction.STORMLANDS);
        GOTEntityRegistry.register(GOTEntityStormlandsMiner.class, id++, GOTFaction.STORMLANDS);
        GOTEntityRegistry.register(GOTEntityStormlandsLumberman.class, id++, GOTFaction.STORMLANDS);
        GOTEntityRegistry.register(GOTEntityStormlandsMason.class, id++, GOTFaction.STORMLANDS);

        GOTEntityRegistry.register(GOTEntityReachMan.class, id++, GOTFaction.REACH);
        GOTEntityRegistry.register(GOTEntityReachLevyman.class, id++, GOTFaction.REACH);
        GOTEntityRegistry.register(GOTEntityReachLevymanArcher.class, id++, GOTFaction.REACH);
        GOTEntityRegistry.register(GOTEntityReachSoldier.class, id++, GOTFaction.REACH);
        GOTEntityRegistry.register(GOTEntityReachSoldierArcher.class, id++, GOTFaction.REACH);
        GOTEntityRegistry.register(GOTEntityReachGuard.class, id++, GOTFaction.REACH);
        GOTEntityRegistry.register(GOTEntityReachBannerBearer.class, id++, GOTFaction.REACH);
        GOTEntityRegistry.register(GOTEntityReachCaptain.class, id++, GOTFaction.REACH);
        GOTEntityRegistry.register(GOTEntityReachBaker.class, id++, GOTFaction.REACH);
        GOTEntityRegistry.register(GOTEntityReachBartender.class, id++, GOTFaction.REACH);
        GOTEntityRegistry.register(GOTEntityReachBlacksmith.class, id++, GOTFaction.REACH);
        GOTEntityRegistry.register(GOTEntityReachGoldsmith.class, id++, GOTFaction.REACH);
        GOTEntityRegistry.register(GOTEntityReachBrewer.class, id++, GOTFaction.REACH);
        GOTEntityRegistry.register(GOTEntityReachButcher.class, id++, GOTFaction.REACH);
        GOTEntityRegistry.register(GOTEntityReachFarmer.class, id++, GOTFaction.REACH);
        GOTEntityRegistry.register(GOTEntityReachFarmhand.class, id++, GOTFaction.REACH);
        GOTEntityRegistry.register(GOTEntityReachFishmonger.class, id++, GOTFaction.REACH);
        GOTEntityRegistry.register(GOTEntityReachFlorist.class, id++, GOTFaction.REACH);
        GOTEntityRegistry.register(GOTEntityReachMiner.class, id++, GOTFaction.REACH);
        GOTEntityRegistry.register(GOTEntityReachLumberman.class, id++, GOTFaction.REACH);
        GOTEntityRegistry.register(GOTEntityReachMason.class, id++, GOTFaction.REACH);

        GOTEntityRegistry.register(GOTEntityDorneMan.class, id++, GOTFaction.DORNE);
        GOTEntityRegistry.register(GOTEntityDorneLevyman.class, id++, GOTFaction.DORNE);
        GOTEntityRegistry.register(GOTEntityDorneLevymanArcher.class, id++, GOTFaction.DORNE);
        GOTEntityRegistry.register(GOTEntityDorneSoldier.class, id++, GOTFaction.DORNE);
        GOTEntityRegistry.register(GOTEntityDorneSoldierArcher.class, id++, GOTFaction.DORNE);
        GOTEntityRegistry.register(GOTEntityDorneBannerBearer.class, id++, GOTFaction.DORNE);
        GOTEntityRegistry.register(GOTEntityDorneCaptain.class, id++, GOTFaction.DORNE);
        GOTEntityRegistry.register(GOTEntityDorneBaker.class, id++, GOTFaction.DORNE);
        GOTEntityRegistry.register(GOTEntityDorneBartender.class, id++, GOTFaction.DORNE);
        GOTEntityRegistry.register(GOTEntityDorneBlacksmith.class, id++, GOTFaction.DORNE);
        GOTEntityRegistry.register(GOTEntityDorneGoldsmith.class, id++, GOTFaction.DORNE);
        GOTEntityRegistry.register(GOTEntityDorneBrewer.class, id++, GOTFaction.DORNE);
        GOTEntityRegistry.register(GOTEntityDorneButcher.class, id++, GOTFaction.DORNE);
        GOTEntityRegistry.register(GOTEntityDorneFarmer.class, id++, GOTFaction.DORNE);
        GOTEntityRegistry.register(GOTEntityDorneFarmhand.class, id++, GOTFaction.DORNE);
        GOTEntityRegistry.register(GOTEntityDorneFishmonger.class, id++, GOTFaction.DORNE);
        GOTEntityRegistry.register(GOTEntityDorneFlorist.class, id++, GOTFaction.DORNE);
        GOTEntityRegistry.register(GOTEntityDorneMiner.class, id++, GOTFaction.DORNE);
        GOTEntityRegistry.register(GOTEntityDorneLumberman.class, id++, GOTFaction.DORNE);
        GOTEntityRegistry.register(GOTEntityDorneMason.class, id++, GOTFaction.DORNE);

        GOTEntityRegistry.register(GOTEntityGoldenWarrior.class, id++, 0xffd700);
        GOTEntityRegistry.register(GOTEntityGoldenSpearman.class, id++, 0xffd700);
        GOTEntityRegistry.register(GOTEntityGoldenBannerBearer.class, id++, 0xffd700);
        GOTEntityRegistry.register(GOTEntityGoldenCaptain.class, id++, 0xffd700);

        GOTEntityRegistry.registerHidden(GOTEntityEnt.class, id++);
        GOTEntityRegistry.registerHidden(GOTEntityDarkHuorn.class, id++);

        GOTEntityRegistry.register(GOTEntityUlthosSpider.class, id++, GOTFaction.HIGH_POWER);
        GOTEntityRegistry.register(GOTEntityBlizzard.class, id++, GOTFaction.WHITE_WALKER);
        GOTEntityRegistry.registerHidden(GOTEntityPortal.class, id++, 80, 3, true);
        GOTEntityRegistry.registerHidden(GOTEntitySmokeRing.class, id++, 64, 10, true);
        GOTEntityRegistry.registerHidden(GOTEntityBomb.class, id++, 160, 10, true);
        GOTEntityRegistry.registerHidden(GOTEntitySpear.class, id++, 64, Integer.MAX_VALUE, false);
        GOTEntityRegistry.registerHidden(GOTEntityPlate.class, id++, 64, 3, true);
        GOTEntityRegistry.registerHidden(GOTEntityThrowingAxe.class, id++, 64, Integer.MAX_VALUE, false);
        GOTEntityRegistry.registerHidden(GOTEntityCrossbowBolt.class, id++, 64, Integer.MAX_VALUE, false);
        GOTEntityRegistry.registerHidden(GOTEntityPebble.class, id++, 64, 3, true);
        GOTEntityRegistry.registerHidden(GOTEntityMysteryWeb.class, id++, 64, 10, true);
        GOTEntityRegistry.registerHidden(GOTEntityTraderRespawn.class, id++, 80, 3, true);
        GOTEntityRegistry.registerHidden(GOTEntityThrownRock.class, id++, 64, 10, true);
        GOTEntityRegistry.registerHidden(GOTEntityBarrel.class, id++, 80, 3, true);
        GOTEntityRegistry.registerHidden(GOTEntityInvasionSpawner.class, id++, 80, 3, true);
        GOTEntityRegistry.registerHidden(GOTEntityThrownTermite.class, id++, 64, 10, true);
        GOTEntityRegistry.registerHidden(GOTEntityConker.class, id++, 64, 3, true);
        GOTEntityRegistry.registerHidden(GOTEntityFishHook.class, id++, 64, 5, true);
        GOTEntityRegistry.registerHidden(GOTEntityDart.class, id++, 64, Integer.MAX_VALUE, false);
        GOTEntityRegistry.registerHidden(GOTEntityNPCRespawner.class, id++, 80, 3, true);
        GOTEntityRegistry.registerHidden(GOTEntityFallingTreasure.class, id++, 160, 20, true);
        GOTEntityRegistry.registerHidden(GOTEntityFallingFireJar.class, id++, 160, 20, true);
        GOTEntityRegistry.registerHidden(GOTEntityFirePot.class, id++, 64, 3, true);
        GOTEntityRegistry.registerHidden(GOTEntityArrowPoisoned.class, id++, 64, 20, false);
        GOTEntityRegistry.registerHidden(GOTEntityArrowFire.class, id++, 64, 20, false);
        GOTEntityRegistry.registerHidden(GOTEntityLionRug.class, id++, 80, 3, true);
        GOTEntityRegistry.registerHidden(GOTEntityBearRug.class, id++, 80, 3, true);
        GOTEntityRegistry.registerHidden(GOTEntityGiraffeRug.class, id++, 80, 3, true);
        GOTEntityRegistry.registerHidden(GOTEntityBanner.class, id++, 160, 3, true);
        GOTEntityRegistry.registerHidden(GOTEntityBannerWall.class, id++, 160, Integer.MAX_VALUE, false);
        GOTEntityRegistry.registerHidden(GOTEntityLingeringPotion.class, id++, 64, 10, true);
        GOTEntityRegistry.registerHidden(GOTEntityLingeringEffect.class, id++, 64, 1, true);
        GOTEntityRegistry.registerHidden(GOTEntityCargocart.class, id++, 80, 20, false);
        GOTEntityRegistry.registerHidden(GOTEntityPlowcart.class, id++, 80, 20, false);
        GOTEntityRegistry.registerHidden(GOTEntityMarshWraithBall.class, id++, 64, 10, true);
        GOTEntityRegistry.registerHidden(GOTEntitySnowball.class, id++, 64, 1, true);
        GOTEntityRegistry.registerHidden(GOTEntityThrowingKnife.class, id++, 64, Integer.MAX_VALUE, false);
        GOTEntityRegistry.registerHidden(GOTEntityArrowSerrated.class, id++, 64, 20, false);
        GOTEntityRegistry.registerHidden(GOTEntityPotionExtra.class, id++, 64, 3, true);
        GOTEntityRegistry.registerHidden(GOTEntityThrowingBomb.class, id++, 64, 3, true);
        GOTEntityRegistry.registerHidden(GOTEntityCustomPotion.class, id++, 64, 3, true);
        GOTEntityRegistry.registerHidden(GOTEntityThiefKnife.class, id++, 64, Integer.MAX_VALUE, false);
        GOTEntityRegistry.registerHidden(GOTEntityToxinBomb.class, id++, 64, 10, true);
        GOTEntityRegistry.registerHidden(GOTEntityLingeringBombEffect.class, id++, 64, 1, true);
        GOTEntityRegistry.registerHidden(GOTEntitySmoke.class, id++, 64, 10, true);
        GOTEntityRegistry.registerHidden(GOTEntitySmokeEffect.class, id++, 64, 1, true);
        GOTEntityRegistry.registerHidden(GOTEntityBattleRam.class, id++);
        GOTEntityRegistry.registerHidden(GOTEntityWildfireBomb.class, id++);
    }
}