package got.client.render;

import java.util.HashMap;
import java.util.Map;

import got.client.effect.GOTEntityAlignmentBonus;
import got.client.effect.GOTEntityDeadMarshFace;
import got.client.render.animal.GOTRenderBear;
import got.client.render.animal.GOTRenderBearRug;
import got.client.render.animal.GOTRenderBird;
import got.client.render.animal.GOTRenderBison;
import got.client.render.animal.GOTRenderBoar;
import got.client.render.animal.GOTRenderButterfly;
import got.client.render.animal.GOTRenderCamel;
import got.client.render.animal.GOTRenderCrocodile;
import got.client.render.animal.GOTRenderDeer;
import got.client.render.animal.GOTRenderDikDik;
import got.client.render.animal.GOTRenderDirewolf;
import got.client.render.animal.GOTRenderDragon;
import got.client.render.animal.GOTRenderElephant;
import got.client.render.animal.GOTRenderFish;
import got.client.render.animal.GOTRenderFlamingo;
import got.client.render.animal.GOTRenderGemsbok;
import got.client.render.animal.GOTRenderGiraffe;
import got.client.render.animal.GOTRenderGiraffeRug;
import got.client.render.animal.GOTRenderHorse;
import got.client.render.animal.GOTRenderLion;
import got.client.render.animal.GOTRenderLionRug;
import got.client.render.animal.GOTRenderMammoth;
import got.client.render.animal.GOTRenderManticore;
import got.client.render.animal.GOTRenderMidges;
import got.client.render.animal.GOTRenderRabbit;
import got.client.render.animal.GOTRenderRedScorpion;
import got.client.render.animal.GOTRenderRhino;
import got.client.render.animal.GOTRenderScorpion;
import got.client.render.animal.GOTRenderShadowcat;
import got.client.render.animal.GOTRenderSnowBear;
import got.client.render.animal.GOTRenderSwan;
import got.client.render.animal.GOTRenderTermite;
import got.client.render.animal.GOTRenderWalrus;
import got.client.render.animal.GOTRenderWhiteBison;
import got.client.render.animal.GOTRenderWhiteOryx;
import got.client.render.animal.GOTRenderWoolyRhino;
import got.client.render.animal.GOTRenderWyvern;
import got.client.render.animal.GOTRenderZebra;
import got.client.render.npc.GOTRenderFactionNPC;
import got.client.render.npc.GOTRenderFactionNPCLayered;
import got.client.render.npc.GOTRenderFactionNPCMonofolder;
import got.client.render.npc.GOTRenderFactionNPCMonotexture;
import got.client.render.npc.GOTRenderGiant;
import got.client.render.npc.GOTRenderIceSpider;
import got.client.render.npc.GOTRenderLegendaryNPC;
import got.client.render.npc.GOTRenderMarshWraith;
import got.client.render.npc.GOTRenderProstitute;
import got.client.render.other.*;
import got.common.database.GOTRegistry;
import got.common.entity.animal.GOTEntityBear;
import got.common.entity.animal.GOTEntityBearRug;
import got.common.entity.animal.GOTEntityBird;
import got.common.entity.animal.GOTEntityBison;
import got.common.entity.animal.GOTEntityBlizzard;
import got.common.entity.animal.GOTEntityBoar;
import got.common.entity.animal.GOTEntityButterfly;
import got.common.entity.animal.GOTEntityCamel;
import got.common.entity.animal.GOTEntityCrocodile;
import got.common.entity.animal.GOTEntityDeer;
import got.common.entity.animal.GOTEntityDikDik;
import got.common.entity.animal.GOTEntityDirewolf;
import got.common.entity.animal.GOTEntityElephant;
import got.common.entity.animal.GOTEntityFish;
import got.common.entity.animal.GOTEntityFlamingo;
import got.common.entity.animal.GOTEntityGemsbok;
import got.common.entity.animal.GOTEntityGiraffe;
import got.common.entity.animal.GOTEntityGiraffeRug;
import got.common.entity.animal.GOTEntityHorse;
import got.common.entity.animal.GOTEntityLionBase;
import got.common.entity.animal.GOTEntityLionRug;
import got.common.entity.animal.GOTEntityMammoth;
import got.common.entity.animal.GOTEntityManticore;
import got.common.entity.animal.GOTEntityMidges;
import got.common.entity.animal.GOTEntityRabbit;
import got.common.entity.animal.GOTEntityRedScorpion;
import got.common.entity.animal.GOTEntityRhino;
import got.common.entity.animal.GOTEntityScorpionBig;
import got.common.entity.animal.GOTEntityShadowcat;
import got.common.entity.animal.GOTEntitySnowBear;
import got.common.entity.animal.GOTEntitySwan;
import got.common.entity.animal.GOTEntityTermite;
import got.common.entity.animal.GOTEntityUlthosSpider;
import got.common.entity.animal.GOTEntityWalrus;
import got.common.entity.animal.GOTEntityWhiteBison;
import got.common.entity.animal.GOTEntityWhiteOryx;
import got.common.entity.animal.GOTEntityWoolyRhino;
import got.common.entity.animal.GOTEntityWyvern;
import got.common.entity.animal.GOTEntityZebra;
import got.common.entity.dragon.GOTEntityDragon;
import got.common.entity.essos.GOTEntityEssosBandit;
import got.common.entity.essos.GOTEntityEssosScrapTrader;
import got.common.entity.essos.GOTEntityEssosThief;
import got.common.entity.essos.GOTEntityIfekevron;
import got.common.entity.essos.GOTEntityRedPriest;
import got.common.entity.essos.GOTEntityShryke;
import got.common.entity.essos.GOTEntityStoneMan;
import got.common.entity.essos.gold.GOTEntityGoldenMan;
import got.common.entity.essos.legendary.quest.GOTEntityJaqenHghar;
import got.common.entity.essos.mossovy.GOTEntityMarshWraith;
import got.common.entity.other.*;
import got.common.entity.potion.GOTEntityLingeringBombEffect;
import got.common.entity.potion.GOTEntityLingeringEffect;
import got.common.entity.potion.GOTEntityLingeringPotion;
import got.common.entity.potion.GOTEntitySmoke;
import got.common.entity.potion.GOTEntitySmokeEffect;
import got.common.entity.potion.GOTEntityToxinBomb;
import got.common.entity.westeros.GOTEntityMaester;
import got.common.entity.westeros.GOTEntityMercenary;
import got.common.entity.westeros.GOTEntitySepton;
import got.common.entity.westeros.GOTEntityWesterosBandit;
import got.common.entity.westeros.GOTEntityWesterosScrapTrader;
import got.common.entity.westeros.GOTEntityWesterosThief;
import got.common.entity.westeros.arryn.GOTEntityArrynMan;
import got.common.entity.westeros.crownlands.GOTEntityCrownlandsAlchemist;
import got.common.entity.westeros.crownlands.GOTEntityCrownlandsMan;
import got.common.entity.westeros.dorne.GOTEntityDorneMan;
import got.common.entity.westeros.dragonstone.GOTEntityDragonstoneMan;
import got.common.entity.westeros.gift.GOTEntityGiftMan;
import got.common.entity.westeros.hillmen.GOTEntityHillman;
import got.common.entity.westeros.hillmen.GOTEntityHillmanWarrior;
import got.common.entity.westeros.ice.GOTEntityIceSpider;
import got.common.entity.westeros.ice.GOTEntityWhiteWalker;
import got.common.entity.westeros.ice.GOTEntityWight;
import got.common.entity.westeros.ice.GOTEntityWightGiant;
import got.common.entity.westeros.ironborn.GOTEntityIronbornMan;
import got.common.entity.westeros.ironborn.GOTEntityIronbornPriest;
import got.common.entity.westeros.north.GOTEntityNorthMan;
import got.common.entity.westeros.north.hillmen.GOTEntityNorthHillman;
import got.common.entity.westeros.north.hillmen.GOTEntityNorthHillmanWarrior;
import got.common.entity.westeros.reach.GOTEntityReachMan;
import got.common.entity.westeros.riverlands.GOTEntityRiverlandsMan;
import got.common.entity.westeros.stormlands.GOTEntityStormlandsMan;
import got.common.entity.westeros.westerlands.GOTEntityWesterlandsMan;
import got.common.entity.westeros.wildling.GOTEntityGiant;
import got.common.entity.westeros.wildling.GOTEntityWildling;
import got.common.entity.westeros.wildling.thenn.GOTEntityThenn;
import got.common.entity.westeros.wildling.thenn.GOTEntityThennBerserker;
import net.minecraft.client.renderer.entity.Render;
import net.minecraft.client.renderer.entity.RenderSnowball;
import net.minecraft.entity.Entity;
import net.minecraft.entity.projectile.EntityPotion;
import net.minecraft.init.Items;

public class GOTRender {
    public static Map<Class<? extends Entity>, Render> renders = new HashMap<>();

    public static void onInit() {
        renders.put(GOTEntityBlizzard.class, new GOTRenderBlizzard());
        renders.put(GOTEntityShryke.class, new GOTRenderFactionNPCLayered("essos/shryke"));
        renders.put(GOTEntityHillman.class, new GOTRenderFactionNPCLayered("westeros/wild"));
        renders.put(GOTEntityNorthHillman.class, new GOTRenderFactionNPCLayered("westeros/wild"));
        renders.put(GOTEntityArrynMan.class, new GOTRenderFactionNPC("westeros/westeros"));
        renders.put(GOTEntityCrownlandsMan.class, new GOTRenderFactionNPC("westeros/westeros"));
        renders.put(GOTEntityDorneMan.class, new GOTRenderFactionNPC("westeros/dorne"));
        renders.put(GOTEntityDragonstoneMan.class, new GOTRenderFactionNPC("westeros/westeros"));
        renders.put(GOTEntityGiftMan.class, new GOTRenderFactionNPC("westeros/gift"));
        renders.put(GOTEntityGoldenMan.class, new GOTRenderFactionNPC("essos/free"));
        renders.put(GOTEntityHillmanWarrior.class, new GOTRenderFactionNPC("westeros/wild"));
        renders.put(GOTEntityIronbornMan.class, new GOTRenderFactionNPC("westeros/ironborn"));
        renders.put(GOTEntityNorthMan.class, new GOTRenderFactionNPC("westeros/north"));
        renders.put(GOTEntityNorthHillmanWarrior.class, new GOTRenderFactionNPC("westeros/wild"));
        renders.put(GOTEntityReachMan.class, new GOTRenderFactionNPC("westeros/westeros"));
        renders.put(GOTEntityRiverlandsMan.class, new GOTRenderFactionNPC("westeros/westeros"));
        renders.put(GOTEntityStormlandsMan.class, new GOTRenderFactionNPC("westeros/westeros"));
        renders.put(GOTEntityThenn.class, new GOTRenderFactionNPC("westeros/thenn"));
        renders.put(GOTEntityWesterlandsMan.class, new GOTRenderFactionNPC("westeros/westeros"));
        renders.put(GOTEntityWight.class, new GOTRenderFactionNPC("westeros/ice/wight"));
        renders.put(GOTEntityWildling.class, new GOTRenderFactionNPC("westeros/wild"));
        renders.put(GOTEntitySepton.class, new GOTRenderFactionNPCLayered("westeros/westeros", "septon"));
        renders.put(GOTEntityRedPriest.class, new GOTRenderFactionNPCLayered("essos/asshai", "priest"));
        renders.put(GOTEntityIronbornPriest.class, new GOTRenderFactionNPCLayered("westeros/ironborn", "priest"));
        renders.put(GOTEntityIfekevron.class, new GOTRenderFactionNPCLayered("essos/ibben"));
        renders.put(GOTEntityMercenary.class, new GOTRenderFactionNPCLayered("westeros/westeros", "mercenary"));
        renders.put(GOTEntityJaqenHghar.class, new GOTRenderLegendaryNPC("jaqen_hghar"));
        renders.put(GOTEntityWesterosThief.class, new GOTRenderFactionNPC("westeros/unreliable"));
        renders.put(GOTEntityEssosThief.class, new GOTRenderFactionNPC("essos/unreliable"));
        renders.put(GOTEntityWesterosBandit.class, new GOTRenderFactionNPC("westeros/unreliable"));
        renders.put(GOTEntityEssosBandit.class, new GOTRenderFactionNPC("essos/unreliable"));
        renders.put(GOTEntityWesterosScrapTrader.class, new GOTRenderFactionNPC("westeros/unreliable"));
        renders.put(GOTEntityEssosScrapTrader.class, new GOTRenderFactionNPC("essos/unreliable"));
        renders.put(GOTEntityMaester.class, new GOTRenderFactionNPCLayered("westeros/westeros", "maester"));
        renders.put(GOTEntityStoneMan.class, new GOTRenderFactionNPC("essos/stone"));
        renders.put(GOTEntityThennBerserker.class, new GOTRenderFactionNPCMonofolder("westeros/thenn/male", 1.1f));
        renders.put(GOTEntityProstitute.class, new GOTRenderProstitute());
        renders.put(GOTEntityCrownlandsAlchemist.class, new GOTRenderFactionNPCLayered("westeros/westeros", "alchemist"));
        renders.put(GOTEntityWhiteWalker.class, new GOTRenderFactionNPCMonotexture("westeros/ice/walker"));
        renders.put(EntityPotion.class, new RenderSnowball(Items.potionitem, 16384));
        renders.put(GOTEntityAlignmentBonus.class, new GOTRenderAlignmentBonus());
        renders.put(GOTEntityArrowPoisoned.class, new GOTRenderArrowPoisoned());
        renders.put(GOTEntityArrowFire.class, new GOTRenderArrowFire());
        renders.put(GOTEntityBison.class, new GOTRenderBison());
        renders.put(GOTEntityBanner.class, new GOTRenderBanner());
        renders.put(GOTEntityBannerWall.class, new GOTRenderBannerWall());
        renders.put(GOTEntityBarrel.class, new GOTRenderBarrel());
        renders.put(GOTEntityBarrowWight.class, new GOTRenderBarrowWight());
        renders.put(GOTEntityBear.class, new GOTRenderBear());
        renders.put(GOTEntityBearRug.class, new GOTRenderBearRug());
        renders.put(GOTEntityBird.class, new GOTRenderBird());
        renders.put(GOTEntityBomb.class, new GOTRenderBomb());
        renders.put(GOTEntityButterfly.class, new GOTRenderButterfly());
        renders.put(GOTEntityCamel.class, new GOTRenderCamel());
        renders.put(GOTEntityCargocart.class, new GOTRenderCargocart());
        renders.put(GOTEntitySnowball.class, new RenderSnowball(Items.snowball));
        renders.put(GOTEntityConker.class, new RenderSnowball(GOTRegistry.chestnut));
        renders.put(GOTEntityCrocodile.class, new GOTRenderCrocodile());
        renders.put(GOTEntityCrossbowBolt.class, new GOTRenderCrossbowBolt());
        renders.put(GOTEntityDart.class, new GOTRenderDart());
        renders.put(GOTEntityDeer.class, new GOTRenderDeer());
        renders.put(GOTEntityDikDik.class, new GOTRenderDikDik());
        renders.put(GOTEntityDirewolf.class, new GOTRenderDirewolf());
        renders.put(GOTEntityDragon.class, new GOTRenderDragon());
        renders.put(GOTEntityElephant.class, new GOTRenderElephant());
        renders.put(GOTEntityFallingFireJar.class, new GOTRenderFallingFireJar());
        renders.put(GOTEntityFallingTreasure.class, new GOTRenderFallingCoinPile());
        renders.put(GOTEntityFirePot.class, new RenderSnowball(GOTRegistry.firePot));
        renders.put(GOTEntityFish.class, new GOTRenderFish());
        renders.put(GOTEntityFlamingo.class, new GOTRenderFlamingo());
        renders.put(GOTEntityGemsbok.class, new GOTRenderGemsbok());
        renders.put(GOTEntityGiant.class, new GOTRenderGiant("giant"));
        renders.put(GOTEntityGiraffe.class, new GOTRenderGiraffe());
        renders.put(GOTEntityGiraffeRug.class, new GOTRenderGiraffeRug());
        renders.put(GOTEntityHorse.class, new GOTRenderHorse());
        renders.put(GOTEntityIceSpider.class, new GOTRenderIceSpider());
        renders.put(GOTEntityInvasionSpawner.class, new GOTRenderInvasionSpawner());
        renders.put(GOTEntityWhiteBison.class, new GOTRenderWhiteBison());
        renders.put(GOTEntityLingeringEffect.class, new GOTRenderLingeringEffect());
        renders.put(GOTEntityLingeringPotion.class, new GOTRenderLingeringPotion());
        renders.put(GOTEntityLionBase.class, new GOTRenderLion());
        renders.put(GOTEntityLionRug.class, new GOTRenderLionRug());
        renders.put(GOTEntityMammoth.class, new GOTRenderMammoth());
        renders.put(GOTEntityManticore.class, new GOTRenderManticore());
        renders.put(GOTEntityMidges.class, new GOTRenderMidges());
        renders.put(GOTEntityMysteryWeb.class, new RenderSnowball(GOTRegistry.mysteryWeb));
        renders.put(GOTEntityNPCRespawner.class, new GOTRenderNPCRespawner());
        renders.put(GOTEntityPebble.class, new RenderSnowball(GOTRegistry.pebble));
        renders.put(GOTEntityPlate.class, new GOTRenderPlate());
        renders.put(GOTEntityPlowcart.class, new GOTRenderPlowcart());
        renders.put(GOTEntityPortal.class, new GOTRenderPortal());
        renders.put(GOTEntityRabbit.class, new GOTRenderRabbit());
        renders.put(GOTEntityRedScorpion.class, new GOTRenderRedScorpion());
        renders.put(GOTEntityRhino.class, new GOTRenderRhino());
        renders.put(GOTEntityScorpionBig.class, new GOTRenderScorpion());
        renders.put(GOTEntitySmokeRing.class, new GOTRenderSmokeRing());
        renders.put(GOTEntitySnowBear.class, new GOTRenderSnowBear());
        renders.put(GOTEntitySpear.class, new GOTRenderSpear());
        renders.put(GOTEntitySwan.class, new GOTRenderSwan());
        renders.put(GOTEntityTermite.class, new GOTRenderTermite());
        renders.put(GOTEntityThrowingAxe.class, new GOTRenderThrowingAxe());
        renders.put(GOTEntityThrownRock.class, new GOTRenderThrownRock());
        renders.put(GOTEntityThrownTermite.class, new RenderSnowball(GOTRegistry.termite));
        renders.put(GOTEntityTraderRespawn.class, new GOTRenderTraderRespawn());
        renders.put(GOTEntityUlthosSpider.class, new GOTRenderGiantSpider());
        renders.put(GOTEntityShadowcat.class, new GOTRenderShadowcat());
        renders.put(GOTEntityWalrus.class, new GOTRenderWalrus());
        renders.put(GOTEntityWhiteOryx.class, new GOTRenderWhiteOryx());
        renders.put(GOTEntityWightGiant.class, new GOTRenderGiant("ice"));
        renders.put(GOTEntityBoar.class, new GOTRenderBoar());
        renders.put(GOTEntityWoolyRhino.class, new GOTRenderWoolyRhino());
        renders.put(GOTEntityWyvern.class, new GOTRenderWyvern());
        renders.put(GOTEntityZebra.class, new GOTRenderZebra());
        renders.put(GOTEntityMarshWraith.class, new GOTRenderMarshWraith());
        renders.put(GOTEntityMarshWraithBall.class, new GOTRenderWraithBall());
        renders.put(GOTEntityDeadMarshFace.class, new GOTRenderDeadMarshFace());
        renders.put(GOTEntityEnt.class, new GOTRenderEnt());
        renders.put(GOTEntityHuornBase.class, new GOTRenderHuorn());
        renders.put(GOTEntityPotionExtra.class, new RenderSnowball(GOTRegistry.freezeSplashPotion));
        renders.put(GOTEntityLingeringBombEffect.class, new GOTRenderLingeringEffect());
        renders.put(GOTEntitySmokeEffect.class, new GOTRenderLingeringEffect());
        renders.put(GOTEntityToxinBomb.class, new GOTRenderLingeringPotion());
        renders.put(GOTEntitySmoke.class, new GOTRenderLingeringPotion());
        renders.put(GOTEntityBattleRam.class, new GOTRenderBattleRam());
    }
}
